### ISSUE TITLE
Forstday StackOverflowError

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#100]
Beim SHIFT-Click in der Workbench fliegt man mit einem StackOverflowError aus dem Spiel.

```
    at net.minecraft.inventory.Container.func_75144_a(SourceFile:199)
    at net.minecraft.inventory.Container.func_75133_b(SourceFile:365)
    at net.minecraft.inventory.Container.func_75144_a(SourceFile:199)
    at net.minecraft.inventory.Container.func_75133_b(SourceFile:365)
    at net.minecraft.inventory.Container.func_75144_a(SourceFile:199)
    at net.minecraft.inventory.Container.func_75133_b(SourceFile:365)

-- Affected screen --
Details:
    Screen name: nedelosk.forestday.module.lumberjack.gui.GuiWorkbench
Stacktrace:
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1645)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by DerOliDE** [comment]
Gefixt.
