### ISSUE TITLE
keine Start mit Version 0.3.0a

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#11]
Mit der letzten Version startet das Spiel nicht mehr. Technics bricht schon nach wenigen Sekunden ab.

``` java
[B#283] 2015/04/24 09:55:44 [INFORMATION]  [09:55:44] [main/ERROR] [LaunchWrapper]: A critical problem occurred registering the ASM transformer class am2.preloader.AccessTransformers
[B#283] 2015/04/24 09:55:44 [INFORMATION]  java.lang.IllegalArgumentException: resource AM2_at.cfg not found.
[B#283] 2015/04/24 09:55:44 [INFORMATION]   at com.google.common.base.Preconditions.checkArgument(Preconditions.java:120) ~[guava-15.0.jar:?]
[B#283] 2015/04/24 09:55:44 [INFORMATION]   at com.google.common.io.Resources.getResource(Resources.java:222) ~[guava-15.0.jar:?]
[B#283] 2015/04/24 09:55:44 [INFORMATION]   at cpw.mods.fml.common.asm.transformers.AccessTransformer.readMapFile(AccessTransformer.java:118) ~[modpack.jar:?]
[B#283] 2015/04/24 09:55:44 [INFORMATION]   at cpw.mods.fml.common.asm.transformers.AccessTransformer.<init>(AccessTransformer.java:101) ~[modpack.jar:?]
[B#283] 2015/04/24 09:55:44 [INFORMATION]   at am2.preloader.AccessTransformers.<init>(AccessTransformers.java:10) ~[AccessTransformers.class:?]
[B#283] 2015/04/24 09:55:44 [INFORMATION]   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.7.0_76]
[B#283] 2015/04/24 09:55:44 [INFORMATION]   at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.7.0_76]
[B#283] 2015/04/24 09:55:44 [INFORMATION]   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.7.0_76]
[B#283] 2015/04/24 09:55:44 [INFORMATION]   at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.7.0_76]
[B#283] 2015/04/24 09:55:44 [INFORMATION]   at java.lang.Class.newInstance(Unknown Source) ~[?:1.7.0_76]
[B#283] 2015/04/24 09:55:44 [INFORMATION]   at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88) [launchwrapper-1.11.jar:?]
[B#283] 2015/04/24 09:55:44 [INFORMATION]   at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:101) [modpack.jar:?]
[B#283] 2015/04/24 09:55:44 [INFORMATION]   at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.11.jar:?]
[B#283] 2015/04/24 09:55:44 [INFORMATION]   at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
[B#283] 2015/04/24 09:55:44 [INFORMATION]  [09:55:44] [main/INFO] [FML]: MC located at: C:\Games\Minecraft\Technics\modpacks\shattered-world
[B#283] 2015/04/24 09:55:44 [INFORMATION]  [09:55:44] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#283] 2015/04/24 09:55:44 [INFORMATION]  [09:55:44] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#283] 2015/04/24 09:55:44 [INFORMATION]  [09:55:44] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#283] 2015/04/24 09:55:44 [INFORMATION]  [09:55:44] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#283] 2015/04/24 09:55:44 [INFORMATION]  [09:55:44] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#283] 2015/04/24 09:55:44 [INFORMATION]  [09:55:44] [main/INFO] [INpurePreloader]: Attempting to detect JVM version...
[B#283] 2015/04/24 09:55:44 [INFORMATION]  [09:55:44] [main/INFO] [INpurePreloader]: Detected JVM: 1.7
[B#283] 2015/04/24 09:55:44 [INFORMATION]  [09:55:44] [main/INFO] [INpurePreloader]: Starting library configuration...
[B#283] 2015/04/24 09:55:44 [INFORMATION]  [09:55:44] [main/INFO] [INpureLogInterceptor]: System attached to FML. Now intercepting all logging calls.
[B#283] 2015/04/24 09:55:44 [INFORMATION]  [09:55:44] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#283] 2015/04/24 09:55:44 [INFORMATION]  [09:55:44] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#283] 2015/04/24 09:55:44 [INFORMATION]  [09:55:44] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#283] 2015/04/24 09:55:45 [INFORMATION]  [09:55:45] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#283] 2015/04/24 09:55:45 [INFORMATION]  [09:55:45] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#283] 2015/04/24 09:55:45 [INFORMATION]  [09:55:45] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#283] 2015/04/24 09:55:45 [INFORMATION]  [09:55:45] [main/INFO] [OpenMods]: openmods.config.simple.ConfigProcessor.process(ConfigProcessor.java:73): Parsing config file 'C:\Games\Minecraft\Technics\modpacks\shattered-world\config\OpenModsLibCore.json'
[B#283] 2015/04/24 09:55:45 [INFORMATION]  [09:55:45] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#283] 2015/04/24 09:55:45 [INFORMATION]  [09:55:45] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[B#283] 2015/04/24 09:55:45 [INFORMATION]  Exception in thread "main" [09:55:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NoSuchMethodError: com.google.common.io.CharSource.readLines(Lcom/google/common/io/LineProcessor;)Ljava/lang/Object;
[B#283] 2015/04/24 09:55:45 [INFORMATION]  [09:55:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at cpw.mods.fml.common.asm.transformers.AccessTransformer.processATFile(AccessTransformer.java:125)
[B#283] 2015/04/24 09:55:45 [INFORMATION]  [09:55:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at cpw.mods.fml.common.asm.transformers.AccessTransformer.readMapFile(AccessTransformer.java:120)
[B#283] 2015/04/24 09:55:45 [INFORMATION]  [09:55:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at cpw.mods.fml.common.asm.transformers.AccessTransformer.<init>(AccessTransformer.java:101)
[B#283] 2015/04/24 09:55:45 [INFORMATION]  [09:55:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at cpw.mods.fml.common.asm.transformers.AccessTransformer.<init>(AccessTransformer.java:97)
[B#283] 2015/04/24 09:55:45 [INFORMATION]  [09:55:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[B#283] 2015/04/24 09:55:45 [INFORMATION]  [09:55:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[B#283] 2015/04/24 09:55:45 [INFORMATION]  [09:55:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[B#283] 2015/04/24 09:55:45 [INFORMATION]  [09:55:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at java.lang.reflect.Constructor.newInstance(Unknown Source)
[B#283] 2015/04/24 09:55:45 [INFORMATION]  [09:55:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at java.lang.Class.newInstance(Unknown Source)
[B#283] 2015/04/24 09:55:45 [INFORMATION]  [09:55:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
[B#283] 2015/04/24 09:55:45 [INFORMATION]  [09:55:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at cpw.mods.fml.common.launcher.FMLDeobfTweaker.injectIntoClassLoader(FMLDeobfTweaker.java:32)
[B#283] 2015/04/24 09:55:45 [INFORMATION]  [09:55:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[B#283] 2015/04/24 09:55:45 [INFORMATION]  [09:55:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by krakel** [comment]
wenn ich 1.7.10_AM2-1.4.0.008.jar mal kurz raus nehme kommt die Exception mit AM2 zwar nicht mehr, aber die letzte Exception bleibt

**Comment by krakel** [comment]
Auch wenn ich alle Mods mal entferne oder komplett neu installiere geht es nicht. Da ist was schon beim Initialisieren was falsch.

**Comment by combak** [comment]
Interessant ich hab das alles im Vanilla Launcher und da läufts :-S (Oli)

**Comment by combak** [comment]
Ich starte jetzt mal ein Versuch mit einer aktuelleren Forge Verion, wenn das nicht hinhaut gibt es wieder ein downgrade auf 1355. (Oli)

**Comment by combak** [comment]
Okay der Fehler liegt am Launcher bzw. das er eine alte Version von den Guava Libraries anfordert, da werde ich wohl im bin-Verzeichnis noch die 1.7.10.json bereitstellen müssen und explizit die Version 16 anstatt 15 verlangen müssen. (Oli)

**Comment by krakel** [comment]
Sowas hatte ich auch irgendwo gelesen, aber nicht verstanden.
Im Doc hatte ich auch geschrieben, das Phönix den Download anders macht und nicht eine zip bietet, sondern alle Mods einzeln. Vielleicht kannst du dann wieder den Kartenmod zurück wechseln.

**Comment by krakel** [comment]
Könntest du so lange wie noch nichts anderes verfügbar ist die Ex Nihilo Automation an lassen.
options:
B:"sieve automation allowed"=true

Außerdem die AgriCraft Configuration
B:GenerateDefaults=true
Generiert einmalig die Rezepte und stellt sich dann automatisch auf false.

**Comment by combak** [comment]
Problem mit Version 0.3.0c gefixt.

Ich kann in die nächste Version  Ex Astris rein nehmen solang musst Du Dir die Automatisierung selbst einschalten. (Oli)
