### ISSUE TITLE
Absturz in NEI beim Betrachten der "Uses" von Mystical White Flower

### ISSUE THREAD

**Issue by BakermanLP** [combak/ShatteredWorld#48]
Kann repariert werden indem folgende Mod Versionen eingesetzt werden:
- appliedenergistics2-rv2-stable-1.jar
- NotEnoughItems-1.7.10-1.0.4.106-universal.jar
- CodeChickenCore-1.7.10-1.0.6.43-universal.jar

Nach diesen Updates geht es dann.

**Comment by BakermanLP** [comment]
Ups, leider immer noch der Absturz ... Hat nicht geholfen, eventuell noch NEIIntegration und neiaddons ein Update verpassen.

**Comment by DerOliDE** [comment]
Eine stable von AE rv2 das ich das noch erleben darf :D

**Comment by krakel** [comment]
Bei mir stürzt da nichts ab, weder bei Key R noch U von NEI. Kann da auch durch alle Rezpte wandern.

**Comment by DerOliDE** [comment]
Probleme die ein NEI Exception verursachen habe ich z.Z. wenn ich die Mine-/ModTweaker Rezepte ingame via /mt reload nachlade, dann bekomme ich folgenden Crash sobald ich irgendwas in NEI nachschlagen möchte.

Crash-Report: http://pastebin.com/AnhvTrMy

**Comment by BakermanLP** [comment]
Hier der gekürzte Crash Report nach drücken der U Taste auf einer Mystical White Flower :

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
        at appeng.integration.modules.NEIHelpers.NEIInscriberRecipeHandler$CachedInscriberRecipe.<init>(NEIInscriberRecipeHandler.java:173)
        at appeng.integration.modules.NEIHelpers.NEIInscriberRecipeHandler.loadUsageRecipes(NEIInscriberRecipeHandler.java:100)
        at codechicken.nei.recipe.TemplateRecipeHandler.loadUsageRecipes(TemplateRecipeHandler.java:346)
        at codechicken.nei.recipe.TemplateRecipeHandler.getUsageHandler(TemplateRecipeHandler.java:471)
        at codechicken.nei.recipe.GuiUsageRecipe.openRecipeGui(GuiUsageRecipe.java:20)
        at codechicken.nei.recipe.RecipeItemInputHandler.lastKeyTyped(RecipeItemInputHandler.java:20)
        at codechicken.nei.guihook.GuiContainerManager.lastKeyTyped(GuiContainerManager.java:307)
        at net.minecraft.client.gui.inventory.GuiContainer.func_73869_a(GuiContainer.java)
        at net.minecraft.client.gui.inventory.GuiContainer.public_func_73869_a(GuiContainer.java)
        at codechicken.nei.guihook.GuiContainerManager.callKeyTyped(GuiContainerManager.java)
        at codechicken.nei.guihook.GuiContainerManager.keyTyped(GuiContainerManager.java:475)
        at codechicken.nei.guihook.GuiContainerManager.handleKeyboardInput(GuiContainerManager.java:465)
        at net.minecraft.client.gui.inventory.GuiContainer.func_146282_l(GuiContainer.java)
        at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276)

**Comment by DerOliDE** [comment]
Das wäre dann der selbe Fehler den ich mit meiner Mine-/ModTweaker Problematik habe.

**Comment by BakermanLP** [comment]
Nur das ich nichts "Reloaded" habe. Vielleicht hängt das mit folgendem Fehler zusammen:

[15:49:52] [Client thread/INFO]: [CHAT] ERROR: Botania.zs:97 > No such static member in minetweaker.item.IItemStack: BotaniaSpreader
[15:49:52] [Client thread/INFO]: [CHAT] ERROR: Botania.zs:97 > No such static member in minetweaker.item.IIngredient: BotaniaLivingwood
[15:49:52] [Client thread/INFO]: [CHAT] ERROR: Botania.zs:97 > No such static member in minetweaker.item.IIngredient: BotaniaLivingwood
[15:49:52] [Client thread/INFO]: [CHAT] ERROR: Botania.zs:97 > No such static member in minetweaker.item.IIngredient: BotaniaLivingwood
[15:49:52] [Client thread/INFO]: [CHAT] ERROR: Botania.zs:97 > No such static member in minetweaker.item.IIngredient: ThaumcraftThaumiumIngot
[15:49:52] [Client thread/INFO]: [CHAT] ERROR: Botania.zs:97 > No such static member in minetweaker.item.IIngredient: ArsMagicaParticleEmitter
[15:49:52] [Client thread/INFO]: [CHAT] ERROR: Botania.zs:97 > No such static member in minetweaker.item.IIngredient: BotaniaLivingwood
[15:49:52] [Client thread/INFO]: [CHAT] ERROR: Botania.zs:97 > No such static member in minetweaker.item.IIngredient: BotaniaLivingwood
[15:49:52] [Client thread/INFO]: [CHAT] ERROR: Botania.zs:97 > No such static member in minetweaker.item.IIngredient: BotaniaLivingwood

Würde zumindest für mich etwas Sinn ergeben.

**Comment by DerOliDE** [comment]
Der Fehler in der Botania.zs (https://github.com/combak/ShatteredWorld/commit/bfa5639a69c122ff95cc6636299b240f4fdb0aa4) ist schon gefixt aber noch nicht in der 0.5.3

**Comment by DerOliDE** [comment]
Wenn ich das entfernen der Inscriber Rezepte auskommentiere stürzt das Spiel nicht mehr nach einem /mt reload ab.

https://github.com/combak/ShatteredWorld/blob/master/scripts/AppliedEnergistics2.zs#L45-L49

**Comment by DerOliDE** [comment]
Cross-Ref: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1602

**Comment by Zixxl** [comment]
Habe den gleichen Fehler bei diversen Mods gesehen, wenn man mit ModTweaker2 Rezepte entfernt. Habe einen Pull Request erstellt, der diesen und weitere ähnliche Fehler behebt. Falls jaredlll08 den Pull Request annimmt, sollte der Fehler mit der nächsten Version von ModTweaker2 behoben sein.

**Comment by DerOliDE** [comment]
Danke für die Bemühung :)

**Comment by BakermanLP** [comment]
Funktioniert in 0.6.1, deswegen: Close

**Comment by DerOliDE** [comment]
Funktioniert nur weil die Fehlerquelle z.Z. auskommentiert wurde. https://github.com/combak/ShatteredWorld/blob/master/scripts/AppliedEnergistics2.zs#L45-L49

Bei ModTweaker wurde der Issue https://github.com/jaredlll08/ModTweaker2/issues/154 erst vor wenigen Stunden geschlossen aber noch keine neue Version daraus gemacht.

**Comment by DerOliDE** [comment]
Fehler mit neuer ModTweaker Version behoben.
