### ISSUE TITLE
Client crash on startup mit 0.5.7 und 0.5.8

### ISSUE THREAD

**Issue by BakermanLP** [combak/ShatteredWorld#79]
Hier der erste Teil des Crash Reports:

Time: 11.06.15 12:58
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.IllegalArgumentException: The name customitems:molten_wrought_iron has been registered twice, for me.otho.customItems.mod.blocks.CustomFluidBlock@49eecc73 and me.otho.customItems.mod.blocks.CustomFluidBlock@23a58a42.
    at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:233)
    at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:182)
    at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:171)
    at me.otho.customItems.registry.BlockRegistry.registerFluid(BlockRegistry.java:739)
    at me.otho.customItems.registry.Registry.register(Registry.java:137)
    at me.otho.customItems.configuration.JsonConfigurationHandler.init(JsonConfigurationHandler.java:79)
    at me.otho.customItems.CustomItems.preInit(CustomItems.java:67)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:533)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:241)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalArgumentException: The name customitems:molten_wrought_iron has been registered twice, for me.otho.customItems.mod.blocks.CustomFluidBlock@49eecc73 and me.otho.customItems.mod.blocks.CustomFluidBlock@23a58a42.
    at cpw.mods.fml.common.registry.FMLControlledNamespacedRegistry.add(FMLControlledNamespacedRegistry.java:380)
    at cpw.mods.fml.common.registry.GameData.registerBlock(GameData.java:889)
    at cpw.mods.fml.common.registry.GameData.registerBlock(GameData.java:864)
    at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:223)
    ... 42 more
-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Linux (amd64) version 3.18.7-gentoo
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 522227512 bytes (498 MB) / 1458044928 bytes (1390 MB) up to 2863661056 bytes (2731 MB)
    JVM Flags: 2 total; -Xmx3072m -XX:MaxPermSize=256m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0

**Comment by DerOliDE** [comment]
Kommt das bei Dir immer oder nur bei bestimmten Situation? Hatte den Crash bis jetzt noch nicht.

**Comment by BakermanLP** [comment]
Immer. Ich habe die neusten beiden Versionen hier am Client noch nie am laufen gehabt.

**Comment by BakermanLP** [comment]
Er hatte scheinbar aus einer früheren Version nicht sauber den config Ordner bereinigt. Es gabe bei mir die Datei gardenstuff-fluids.json und die gardenstuff.json. Damit auch der Fehler. Warum er das aber beim Löschen des Modpacks und neu installieren nicht löscht ist mir ein kleines Rätsel.

**Comment by DerOliDE** [comment]
Blöder Technic Launcher, dann schließe ich hier mal ab.
